auto replair cross# Please enter the commit message for your changes. Lines starting

diff --git a/cross b/cross
--- a/cross
+++ b/cross
@@ -99,6 +99,10 @@ function check_class {
 
 function update_time {
     awk -F [\\t:\'\"]+ -v outtime="$wb/$season/stats/cocacola ranking" '
+    {
+        gsub(/^ */, "", $1)
+        gsub(/ *$/, "", $1)    
+    }
     FNR == NR {
         time[$1] = 0
         counts[$1] = 0
@@ -138,11 +142,21 @@ function update_time {
 }
 
 function update_uci {
-    awk -F \\t 'NR == FNR {
+    awk -F \\t '
+    {
+        gsub(/^ */, "", $1)
+        gsub(/ *$/, "", $1)    
+    }
+    NR == FNR {
         uci[$1] = $2
     } NR != FNR && $1 ~ "^[0-9]+$" {
         awarded[++i] = $1
     } NR != FNR && $1 !~ "^[0-9]+$" {
+        if (!($1 in uci)) {
+            print "#Error: line " FNR >> "../stats/error.log"
+            print "file=" FILENAME >> "../stats/error.log"
+            print "rider=\""$1"\"" >> "../stats/error.log"
+        }
         if (FNR <= i)
             uci[$1] += awarded[FNR]
     }
@@ -154,7 +168,12 @@ function update_uci {
 }
 
 function update_pts {
-    awk -F \\t 'NR == FNR {
+    awk -F \\t '
+    {
+        gsub(/^ */, "", $1)
+        gsub(/ *$/, "", $1)    
+    }
+    NR == FNR {
         pts[$1] = $2
     } NR != FNR && $1 ~ "^[0-9]+$" {
         awarded[++i] = $1
@@ -170,7 +189,12 @@ function update_pts {
 }
 
 function update_palmares {
-    awk -F \\t 'NR == FNR {
+    awk -F \\t '
+    {
+        gsub(/^ */, "", $1)
+        gsub(/ *$/, "", $1)    
+    }
+    NR == FNR {
         first[$1] = $2
         second[$1] = $3
         third[$1] = $4
@@ -195,10 +219,28 @@ function update_palmares {
     }' /tmp/cross_palm * > /tmp/cross_palm_tmp && mv /tmp/cross_palm_tmp /tmp/cross_palm
 }
 
+function auto_replace {
+    cd ../stats
+    echo "break" >> error.log
+    exec 3<error.log
+    while true; do
+        read -u 3 line; eval "$line"
+        read -u 3 line; eval "$line"
+        read -u 3 line; eval "$line"
+        find .. -name "$file"
+        RIDER=$(agrep 2>/dev/null -B "$rider" ../riders <<< "y" | cut -f2 -d')')
+        echo "Error: $rider, did you mean $RIDER?"
+        read -u 1 ans
+        [[ $ans =~ [Yy].* ]] && find .. -name "$file" -exec sed -i "s/$rider/$RIDER/" "{}" \;
+    done < error.log
+}
+
 function update_all {
     cd "$wb/$season"
     cd cocacola
     update_time
+    echo -n > ../stats/error.log
+    
     sed 's/$/\t0/' ../riders > /tmp/cross_points
     for type in "superprestige" "worldcup"; do
         cd ../"$type"
@@ -213,6 +255,14 @@ function update_all {
     sort /tmp/cross_uci -k2 -t$'\t' -nr > ../stats/uci
     sort /tmp/cross_palm -k2,2 -k3,3 -k4,4 -t$'\t' -nr > ../stats/palmares
     rm /tmp/cross*
+    if [[ $(wc -l < ../stats/error.log) -gt 0 ]]; then
+        echo >&2 "E: invalid rider names"
+        cat ../stats/error.log
+        echo "Enter auto replace mode?"
+        read line
+        [[ $line =~ [Yy].* ]] && auto_replace
+        exit 8
+    fi
 }
 
 function next_season {
